controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    manipulator_arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    joint_state_controller:
      type: joint_state_controller/JointStateController

manipulator_arm_controller:
  ros__parameters:
    joints:
      - joint0
      - joint1

    command_interfaces:
      - position

    state_interfaces:
      - position
